/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipeminjaman;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class datapeminjam extends javax.swing.JFrame {

    /**
     * Creates new form datapeminjam
     */
    String a, a1, b, b1, c, c1, d, d1, e, e1, f, f1, g, g1, h, h1, i, j, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z;
    String jk;
    String kdpj, namapeminjam, alamat, nama, kdbk, jdlbuku, jmlhbuku, tglPinjam, tglKembali;
    String getKDP = "", np = "", alm = "", kdbku = "", jb = "", jp = "", pnjm = "", kmbl = "";
    Date date1, date2;
    koneksi k = new koneksi();
    DefaultTableModel tabModel;
    String dateFormat = "yyyy-MM-dd";
    SimpleDateFormat date = new SimpleDateFormat(dateFormat);

    public datapeminjam() {
        initComponents();
        setLocationRelativeTo(null);
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kdpinjam = new javax.swing.JTextField();
        namapinjam = new javax.swing.JTextField();
        kdbuku = new javax.swing.JTextField();
        judulbuku = new javax.swing.JTextField();
        alamatpinjam = new javax.swing.JTextField();
        jmlbuku = new javax.swing.JTextField();
        tglpinjam = new com.toedter.calendar.JDateChooser();
        tglkembali = new com.toedter.calendar.JDateChooser();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(168, 69, 184));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cobo-Book");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kdpinjam.setEditable(false);
        kdpinjam.setBackground(new java.awt.Color(235, 235, 235));
        kdpinjam.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kdpinjam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "KODE PINJAM ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N
        kdpinjam.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        namapinjam.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        namapinjam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "NAMA PEMINJAM ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N

        kdbuku.setEditable(false);
        kdbuku.setBackground(new java.awt.Color(235, 235, 235));
        kdbuku.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kdbuku.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "KODE BUKU ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N

        judulbuku.setEditable(false);
        judulbuku.setBackground(new java.awt.Color(235, 235, 235));
        judulbuku.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        judulbuku.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "JUDUL BUKU ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N

        alamatpinjam.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        alamatpinjam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ALAMAT ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N

        jmlbuku.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jmlbuku.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "JUMLAH BUKU  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N

        tglpinjam.setBackground(new java.awt.Color(255, 255, 255));
        tglpinjam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TANGGAL PINJAM  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N
        tglpinjam.setEnabled(false);

        tglkembali.setBackground(new java.awt.Color(255, 255, 255));
        tglkembali.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TANGGAL KEMBALI  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 10))); // NOI18N
        tglkembali.setEnabled(false);

        edit.setBackground(new java.awt.Color(218, 172, 221));
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("EDIT");
        edit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        edit.setBorderPainted(false);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pinjam", "Nama Peminjam", "Alamat", "Kode Buku", "Judul Buku", "Jumlah Buku", "Tanggal Pinjam", "Tanggal Kembali"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(4).setResizable(false);
            tabel.getColumnModel().getColumn(5).setResizable(false);
            tabel.getColumnModel().getColumn(6).setResizable(false);
            tabel.getColumnModel().getColumn(7).setResizable(false);
        }

        hapus.setBackground(new java.awt.Color(255, 51, 51));
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("DELETE");
        hapus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        hapus.setBorderPainted(false);
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        kembali.setBackground(new java.awt.Color(255, 255, 255));
        kembali.setText("BACK");
        kembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jLabel3.setText("Search By :");

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Categories--", "Kode Pinjam", "Nama Peminjam" }));

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kdpinjam, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namapinjam, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(alamatpinjam, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jmlbuku, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kdbuku)
                        .addComponent(judulbuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kdpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namapinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alamatpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kdbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(judulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void showData() {
        try {
            tabModel = (DefaultTableModel) tabel.getModel();
            tabModel.setRowCount(0);
            k.setDriver();
            k.query = "SELECT * FROM peminjam WHERE kd_pinjam NOT IN (SELECT kd_pinjam FROM pengembalian);";
            k.read();
            while (k.rs.next()) {
                a = k.rs.getString("kd_pinjam");
                b = k.rs.getString("nama_peminjam");
                c = k.rs.getString("alamat");
                d = k.rs.getString("kd_buku");
                e = k.rs.getString("judul_buku");
                f = k.rs.getString("jumlah_buku");
                g = k.rs.getString("tgl_pinjam");
                h = k.rs.getString("tgl_kembali");

                String[] data = {a, b, c, d, e, f, g, h};
                tabModel.addRow(data);
            }
        } catch (Exception ex) {
            System.out.println("Error" + ex);
        }
    }

    protected void clearForm() {
        kdpinjam.setText("");
        namapinjam.setText("");
        alamatpinjam.setText("");
        kdbuku.setText("");
        judulbuku.setText("");
        jmlbuku.setText("");
        tglpinjam.setCalendar(null);
        tglkembali.setCalendar(null);
    }

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        tabModel = (DefaultTableModel) tabel.getModel();

        //cek jika row sudah terisi data minimal ada 1 data
        if (tabel.getSelectedRowCount() == 1) {
            m = kdpinjam.getText();
            n = namapinjam.getText();
            x = alamatpinjam.getText();
            o = kdbuku.getText();
            i = judulbuku.getText();
            j = jmlbuku.getText();

            int q = JOptionPane.showConfirmDialog(null, "Yakin Ingin Mengubah Data Ini?", "Warning", JOptionPane.YES_NO_OPTION);

            if (q == JOptionPane.YES_OPTION) {
                try {
                    k.setDriver();
                    k.query = "update peminjam set kd_pinjam='" + m + "',nama_peminjam='" + n + "',alamat='" + x + "',kd_buku='" + o + "',judul_buku='" + i + "',jumlah_buku='" + j + "' where kd_pinjam='" + m + "'";
                    k.CUD();
                    k.ps.executeUpdate();
                } catch (Exception e) {
                    System.err.println("error" + e);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang dipilih", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        clearForm();
        showData();
    }//GEN-LAST:event_editMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        kdpinjam.setText("");
        namapinjam.setText("");
        alamatpinjam.setText("");
        kdbuku.setText("");
        judulbuku.setText("");
        jmlbuku.setText("");
        tglpinjam.setCalendar(null);
        tglkembali.setCalendar(null);
    }//GEN-LAST:event_clearActionPerformed

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        tabModel = (DefaultTableModel) tabel.getModel();
        //cek jika row sudah terisi data minimal ada 1 data
        if (tabel.getSelectedRowCount() == 1) {
            r = kdpinjam.getText();

            int s = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data Ini?", "Warning", JOptionPane.YES_NO_OPTION);

            if (s == JOptionPane.YES_OPTION) {
                try {
                    k.setDriver();
                    k.query = "delete from peminjam where kd_pinjam='" + r + "'";
                    k.CUD();
                    k.ps.executeUpdate();
                    clearForm();
                    showData();
                } catch (Exception e) {
                    System.err.println("error" + e);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        new MenuData().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        //mengambil row ke-n (row yang aktif) yang di-klik oleh user
        int row = tabel.getSelectedRow();
        getKDP = tabel.getValueAt(row, 0).toString();
        np = tabel.getValueAt(row, 1).toString();
        alm = tabel.getValueAt(row, 2).toString();
        kdbku = tabel.getValueAt(row, 3).toString();
        jb = tabel.getValueAt(row, 4).toString();
        jp = tabel.getValueAt(row, 5).toString();
        pnjm = tabel.getValueAt(row, 6).toString();
        kmbl = tabel.getValueAt(row, 7).toString();

        try {
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(pnjm);
        } catch (ParseException ex) {
            Logger.getLogger(datapeminjam2.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(kmbl);
        } catch (ParseException ex) {
            Logger.getLogger(datapeminjam2.class.getName()).log(Level.SEVERE, null, ex);
        }

        //menampilkan value/nilai dari index row yang dipilih/click ke dalam form
        kdpinjam.setText(getKDP);
        namapinjam.setText(np);
        alamatpinjam.setText(alm);
        kdbuku.setText(kdbku);
        judulbuku.setText(jb);
        jmlbuku.setText(jp);
        tglpinjam.setDate(date2);
        tglkembali.setDate(date1);


    }//GEN-LAST:event_tabelMouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String srcMethod = kategori.getSelectedItem().toString();
        String searchEngine = search.getText();

        if ("Kode Pinjam".equals(srcMethod)) {
            try {
                tabModel = (DefaultTableModel) tabel.getModel();
                tabModel.setRowCount(0);
                k.setDriver();
                k.query = "select * from peminjam where kd_pinjam like '%" + searchEngine + "%'";
                k.read();

                while (k.rs.next()) {
                    a1 = k.rs.getString("kd_pinjam");
                    b1 = k.rs.getString("nama_peminjam");
                    c1 = k.rs.getString("alamat");
                    d1 = k.rs.getString("kd_buku");
                    e1 = k.rs.getString("judul_buku");
                    f1 = k.rs.getString("jumlah_buku");
                    g1 = k.rs.getString("tgl_pinjam");
                    h1 = k.rs.getString("tgl_kembali");

                    String[] data = {a1, b1, c1, d1, e1, f1, g1, h1};
                    tabModel.addRow(data);
                }

            } catch (Exception e) {
                System.out.println("Error" + e);
            }

        } else if ("Nama Peminjam".equals(srcMethod)) {
            try {
                tabModel = (DefaultTableModel) tabel.getModel();
                tabModel.setRowCount(0);
                k.setDriver();
                k.query = "select * from peminjam where nama_peminjam like '%" + searchEngine + "%'";
                k.read();

                while (k.rs.next()) {
                    a1 = k.rs.getString("kd_pinjam");
                    b1 = k.rs.getString("nama_peminjam");
                    c1 = k.rs.getString("alamat");
                    d1 = k.rs.getString("kd_buku");
                    e1 = k.rs.getString("judul_buku");
                    f1 = k.rs.getString("jumlah_buku");
                    g1 = k.rs.getString("tgl_pinjam");
                    h1 = k.rs.getString("tgl_kembali");

                    String[] data = {a1, b1, c1, d1, e1, f1, g1, h1};
                    tabModel.addRow(data);
                }

            } catch (Exception e) {
                System.out.println("Error" + e);
            }
        } else {
            showData();
        }
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapeminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatpinjam;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlbuku;
    public static javax.swing.JTextField judulbuku;
    private static javax.swing.JComboBox<String> kategori;
    public static javax.swing.JTextField kdbuku;
    private javax.swing.JTextField kdpinjam;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField namapinjam;
    private static javax.swing.JTextField search;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tglkembali;
    private com.toedter.calendar.JDateChooser tglpinjam;
    // End of variables declaration//GEN-END:variables
}
