/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipeminjaman;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class datapeminjam2 extends javax.swing.JFrame {

    /**
     * Creates new form datapeminjam2
     */
    DefaultTableModel tabModel;
    koneksi k = new koneksi();
    String a, b, c, d, e, f, g, h;
    String kdpinjam, namapeminjam, alamat, namapinjam, kdbuku, judulbuku, jmlbuku, tglPinjam, tglKembali;
    public static String getKDP = "", np = "", alm = "", jb = "", jp = "", kmbl = "";
    Date date1;

    public datapeminjam2() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        get = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(168, 69, 184));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cobo-Book");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pinjam", "Nama Peminjam", "Alamat", "Kode Buku", "Judul Buku", "Jumlah Buku", "Tanggal Pinjam", "Tanggal Kembali"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        get.setBackground(new java.awt.Color(218, 172, 221));
        get.setText("PILIH DATA");
        get.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        get.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getMouseClicked(evt);
            }
        });
        get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getActionPerformed(evt);
            }
        });

        jLabel3.setText("Search By :");

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Categories--", "Kode Pinjam", "Nama Peminjam" }));

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(get, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(get, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void showData() {
        try {
            tabModel = (DefaultTableModel) tabel.getModel();
            tabModel.setRowCount(0);
            k.setDriver();
            k.query = "SELECT * FROM peminjam WHERE kd_pinjam NOT IN (SELECT kd_pinjam FROM pengembalian);";
            k.read();
            while (k.rs.next()) {
                kdpinjam = k.rs.getString("kd_pinjam");
                namapinjam = k.rs.getString("nama_peminjam");
                alamat = k.rs.getString("alamat");
                kdbuku = k.rs.getString("kd_buku");
                judulbuku = k.rs.getString("judul_buku");
                jmlbuku = k.rs.getString("jumlah_buku");
                tglPinjam = k.rs.getString("tgl_pinjam");
                tglKembali = k.rs.getString("tgl_kembali");

                String[] data = {kdpinjam, namapinjam, alamat, kdbuku, judulbuku, jmlbuku, tglPinjam, tglKembali};
                tabModel.addRow(data);
            }
        } catch (Exception ex) {
            System.out.println("Error" + ex);
        }
    }

    private void getMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getMouseClicked
        // TODO add your handling code here:
        pengembalian.kdpinjam.setText(getKDP);
        pengembalian.namapinjam.setText(np);
        pengembalian.alamatpinjam.setText(alm);
        pengembalian.judulbuku.setText(jb);
        pengembalian.jmlbuku.setText(jp);
        pengembalian.tglkembali.setDate(date1);

        this.dispose();

    }//GEN-LAST:event_getMouseClicked

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        //mengambil row ke-n (row yang aktif) yang di-klik oleh user
        int row = tabel.getSelectedRow();
        getKDP = tabel.getValueAt(row, 0).toString();
        np = tabel.getValueAt(row, 1).toString();
        alm = tabel.getValueAt(row, 2).toString();
        jb = tabel.getValueAt(row, 4).toString();
        jp = tabel.getValueAt(row, 5).toString();
        kmbl = tabel.getValueAt(row, 7).toString();

        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(kmbl);
        } catch (ParseException ex) {
            Logger.getLogger(datapeminjam2.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_tabelMouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String srcMethod = kategori.getSelectedItem().toString();
        String searchEngine = search.getText();

        if ("Kode Pinjam".equals(srcMethod)) {
            try {
                tabModel = (DefaultTableModel) tabel.getModel();
                tabModel.setRowCount(0);
                k.setDriver();
                k.query = "select * from peminjam where kd_pinjam like '%" + searchEngine + "%'";
                k.read();

                while (k.rs.next()) {
                    a = k.rs.getString("kd_pinjam");
                    b = k.rs.getString("nama_peminjam");
                    c = k.rs.getString("alamat");
                    d = k.rs.getString("kd_buku");
                    e = k.rs.getString("judul_buku");
                    f = k.rs.getString("jumlah_buku");
                    g = k.rs.getString("tgl_pinjam");
                    h = k.rs.getString("tgl_kembali");

                    String[] data = {a, b, c, d, e, f, g, h};
                    tabModel.addRow(data);
                }

            } catch (Exception e) {
                System.out.println("Error" + e);
            }

        } else if ("Nama Peminjam".equals(srcMethod)) {
            try {
                tabModel = (DefaultTableModel) tabel.getModel();
                tabModel.setRowCount(0);
                k.setDriver();
                k.query = "select * from peminjam where nama_peminjam like '%" + searchEngine + "%'";
                k.read();

                while (k.rs.next()) {
                    a = k.rs.getString("kd_pinjam");
                    b = k.rs.getString("nama_peminjam");
                    c = k.rs.getString("alamat");
                    d = k.rs.getString("kd_buku");
                    e = k.rs.getString("judul_buku");
                    f = k.rs.getString("jumlah_buku");
                    g = k.rs.getString("tgl_pinjam");
                    h = k.rs.getString("tgl_kembali");

                    String[] data = {a, b, c, d, e, f, g, h};
                    tabModel.addRow(data);
                }

            } catch (Exception e) {
                System.out.println("Error" + e);
            }
        } else {
            showData();
        }
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapeminjam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapeminjam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapeminjam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapeminjam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapeminjam2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton get;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JComboBox<String> kategori;
    private static javax.swing.JTextField search;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
